# Generated by Django 3.2 on 2023-03-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
