# Generated by Django 3.2 on 2023-03-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='index',
        ),
    ]
