# Generated by Django 3.2 on 2023-03-03 13:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
                ('title', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('Vacancy', models.IntegerField(default=1)),
                ('Responsibility', models.TextField(max_length=250)),
                ('Benefits', models.TextField(max_length=250)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('type_job', models.CharField(choices=[('workshops', 'workshops'), ('traninng', 'traninng')], max_length=30, null=True)),
                ('location', models.CharField(max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_owner', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('accept', 'accept'), ('regret', 'regret')], max_length=25, null=True)),
                ('cover_letter', models.TextField(max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status_company', models.CharField(blank=True, choices=[('accept', 'accept'), ('regret', 'regret')], max_length=10, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Job_apply', to='job.job')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_apply', to='accounts.student')),
            ],
        ),
    ]
